import os
import io
import logging
from typing import Optional
from jinja2 import Template
from app.schemas.report import AnalysisReport

logger = logging.getLogger(__name__)

PDF_HTML_TEMPLATE = """
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<style>
  @page {
    size: A4;
    margin: 20mm;
  }
  body {
    font-family: 'Helvetica Neue', Arial, sans-serif;
    color: #1e293b;
    background: #ffffff;
    line-height: 1.5;
    font-size: 12px;
  }
  .header {
    border-bottom: 2px solid #f59e0b;
    padding-bottom: 12px;
    margin-bottom: 20px;
    display: flex;
    justify-content: space-between;
  }
  .brand {
    font-size: 20px;
    font-weight: bold;
    color: #0f172a;
  }
  .sub-brand {
    font-size: 11px;
    color: #64748b;
    text-transform: uppercase;
    letter-spacing: 1px;
  }
  .badge {
    display: inline-block;
    padding: 4px 10px;
    border-radius: 4px;
    font-weight: bold;
    font-size: 11px;
    text-transform: uppercase;
  }
  .badge-critical { background: #fee2e2; color: #dc2626; border: 1px solid #f87171; }
  .badge-high { background: #fef3c7; color: #d97706; border: 1px solid #fbbf24; }
  .badge-review { background: #fef9c3; color: #ca8a04; border: 1px solid #fde047; }
  .badge-low { background: #dcfce7; color: #16a34a; border: 1px solid #86efac; }
  
  .card {
    background: #f8fafc;
    border: 1px solid #e2e8f0;
    border-radius: 6px;
    padding: 12px;
    margin-bottom: 15px;
  }
  .section-title {
    font-size: 14px;
    font-weight: bold;
    color: #0f172a;
    margin-top: 15px;
    margin-bottom: 8px;
    border-bottom: 1px solid #e2e8f0;
    padding-bottom: 4px;
  }
  table {
    width: 100%;
    border-collapse: collapse;
    margin-top: 8px;
    font-size: 11px;
  }
  th, td {
    padding: 6px 8px;
    border: 1px solid #cbd5e1;
    text-align: left;
  }
  th {
    background: #f1f5f9;
    color: #475569;
    font-weight: 600;
  }
  .footer {
    margin-top: 30px;
    border-top: 1px solid #e2e8f0;
    padding-top: 8px;
    font-size: 10px;
    color: #94a3b8;
    text-align: center;
  }
</style>
</head>
<body>

<div class="header">
  <div>
    <div class="brand">IntentShield CTI — Security Analysis Report</div>
    <div class="sub-brand">Explainable Android Malware & Financial Risk Intelligence</div>
  </div>
  <div style="text-align: right;">
    <div>Date: {{ report.scanDate }}</div>
    <div>Job ID: {{ report.jobId }}</div>
  </div>
</div>

<div class="card">
  <table style="border: none; margin: 0;">
    <tr style="border: none;">
      <td style="border: none; width: 60%;">
        <strong>Application:</strong> {{ report.appName }}<br>
        <strong>Package:</strong> {{ report.packageName }}<br>
        <strong>SHA-256:</strong> <code>{{ report.sha256 }}</code><br>
        <strong>File Size:</strong> {{ report.fileSize }}
      </td>
      <td style="border: none; width: 40%; text-align: right; vertical-align: middle;">
        <div style="font-size: 28px; font-weight: bold; color: #0f172a;">
          {{ report.riskScore }} <span style="font-size: 14px; color: #64748b;">/ 100</span>
        </div>
        <div class="badge badge-{{ report.riskLevel }}">{{ report.riskClassification }}</div>
      </td>
    </tr>
  </table>
</div>

<div class="section-title">6-Factor Risk Breakdown Formula</div>
<table>
  <thead>
    <tr>
      <th>Risk Dimension</th>
      <th>Score (0–100)</th>
      <th>Weight</th>
      <th>Description</th>
    </tr>
  </thead>
  <tbody>
    {% for comp in report.riskComponents %}
    <tr>
      <td><strong>{{ comp.name }}</strong></td>
      <td>{{ comp.score }} / 100</td>
      <td>{{ comp.weight }}</td>
      <td>{{ comp.description }}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>

<div class="section-title">Flagged Security Evidence</div>
<ul>
  {% for ev in report.evidence %}
  <li>
    <strong>[{{ ev.severity | upper }}] {{ ev.title }}:</strong> {{ ev.description }}
  </li>
  {% endfor %}
</ul>

<div class="section-title">Attack Pathway & Threat Analysis</div>
<div class="card">
  <strong>{{ report.attackPathway.title }}</strong>
  <p>{{ report.attackPathway.summary }}</p>
  <ol>
    {% for step in report.attackPathway.steps %}
    <li><strong>{{ step.label }} ({{ step.severity | upper }}):</strong> {{ step.description }}</li>
    {% endfor %}
  </ol>
</div>

<div class="section-title">Actionable Analyst Recommendations</div>
<ul>
  {% for rec in report.recommendations %}
  <li>
    <strong>[{{ rec.severity | upper }}] {{ rec.title }}:</strong> {{ rec.guidance }}
  </li>
  {% endfor %}
</ul>

<div class="footer">
  Generated by IntentShield CTI Analysis Platform • Confidential Defensive Security Assessment
</div>

</body>
</html>
"""


def generate_report_pdf(report: AnalysisReport) -> bytes:
    """Generate PDF binary bytes for an AnalysisReport."""
    report_dict = report.model_dump(by_alias=True)
    template = Template(PDF_HTML_TEMPLATE)
    rendered_html = template.render(report=report_dict)

    # 1. Try WeasyPrint
    try:
        from weasyprint import HTML
        pdf_bytes = HTML(string=rendered_html).write_pdf()
        return pdf_bytes
    except Exception as e:
        logger.warning("WeasyPrint not available or failed (%s). Using ReportLab fallback generator.", e)

    # 2. Robust ReportLab Fallback
    try:
        from reportlab.lib.pagesizes import letter
        from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
        from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
        from reportlab.lib import colors

        buffer = io.BytesIO()
        doc = SimpleDocTemplate(buffer, pagesize=letter, rightMargin=36, leftMargin=36, topMargin=36, bottomMargin=36)
        styles = getSampleStyleSheet()

        story = []
        title_style = ParagraphStyle(name="TitleStyle", parent=styles["Heading1"], fontSize=16, leading=20, textColor=colors.HexColor("#0f172a"))
        h2_style = ParagraphStyle(name="H2Style", parent=styles["Heading2"], fontSize=12, leading=16, textColor=colors.HexColor("#b45309"))
        body_style = ParagraphStyle(name="BodyStyle", parent=styles["BodyText"], fontSize=9, leading=12)

        story.append(Paragraph("<b>IntentShield CTI — Security Analysis Report</b>", title_style))
        story.append(Paragraph(f"Application: {report.app_name} | Package: {report.package_name}", body_style))
        story.append(Paragraph(f"SHA-256: {report.sha256}", body_style))
        story.append(Paragraph(f"Risk Score: <b>{report.risk_score}/100</b> ({report.risk_classification})", body_style))
        story.append(Spacer(1, 10))

        story.append(Paragraph("<b>6-Factor Risk Breakdown</b>", h2_style))
        table_data = [["Dimension", "Score", "Weight", "Description"]]
        for c in report.risk_components:
            table_data.append([c.name, f"{c.score}/100", str(c.weight), Paragraph(c.description or "", body_style)])

        t = Table(table_data, colWidths=[110, 60, 50, 320])
        t.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#f1f5f9")),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.HexColor("#334155")),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#cbd5e1")),
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
            ("FONTSIZE", (0, 0), (-1, -1), 8),
        ]))
        story.append(t)
        story.append(Spacer(1, 10))

        story.append(Paragraph("<b>Security Evidence & Indicators</b>", h2_style))
        for ev in report.evidence:
            story.append(Paragraph(f"• <b>[{ev.severity.upper()}] {ev.title}</b>: {ev.description}", body_style))
        story.append(Spacer(1, 10))

        story.append(Paragraph("<b>Analyst Recommendations</b>", h2_style))
        for rec in report.recommendations:
            story.append(Paragraph(f"• <b>[{rec.severity.upper()}] {rec.title}</b>: {rec.guidance}", body_style))

        doc.build(story)
        return buffer.getvalue()
    except Exception as e2:
        logger.error("PDF generation failed: %s", e2)
        # Fallback to plain text bytes
        return f"IntentShield Security Report\nApp: {report.appName}\nScore: {report.riskScore}/100".encode("utf-8")
